### PR TITLE
Revert "Pimpup switch"

### PR DESCRIPTION
**Pull request by anirudhgupta109**
This reverts commit 0df51420cf7e2314d376975f82b609f2e54523ad.
needed since the pimling of substratum themes is ruined and our inbuilt accent changer

### CODE REVIEW

**Comment by Anandnv** [comment]
We can add accent color instead of reverting back to stock.one 😂

**Comment by krasCGQ** [comment]
@Anandnv Add.
Sum.
Moar.
Memes.

**Comment by rk779** [comment]
@krasCGQ lol

**Comment by rk779** [comment]
@rk779 By me ?

**Comment by anirudhgupta109** [comment]
@Anandnv Stock is best though

**Pull request closed without merging**
