### PR TITLE
Remove CarrierDefaultApp since it causes no data on Airtel

### PR DESCRIPTION
**Pull request by anirudhgupta109**
Google had the bright idea to add a Balance checker to data connections to prevent additional costs after the plan expires, sadly Airtel hasn't adapted to it and causes no data connectivity because of it.
Please test this on Jio and other carriers

### CODE REVIEW

**Comment by Ayushd70** [comment]
@anirudhgupta109 Airtel ;(

**Comment by krasCGQ** [comment]
@anirudhgupta109 Even Telkomsel & XL Axiata of Indonesia do

**Comment by Rpingat** [comment]
Gonna close this PR😂

**Comment by anirudhgupta109** [comment]
@Rpingat Why ;-;

**Comment by Rpingat** [comment]
@anirudhgupta109 You can do that before compiling for yourself what if other sim cards need it?

**Comment by anirudhgupta109** [comment]
@Rpingat Reason why I added, please check on other carriers

**Pull request closed without merging**
